version: "3"

services: 
  elasticsearch:
    image: elasticsearch:7.9.3
    deploy:
        placement:
            constraints: [node.role == manager]
    ports:
      - 9200:9200
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - logging-network

  logstash:
    image: logstash:7.9.3
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - /root/docker-elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - logging-network

  kibana:
    image: kibana:7.9.3
    depends_on:
      - logstash
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    deploy:
        placement: 
            constraints: [node.role == manager]
    ports: 
      - 5601:5601
    networks: 
      - logging-network

  #httpd:
    #image: httpd:latest
    #depends_on:
      #- logstash
    #ports:
      #- 80:80
    #logging:
      #driver: gelf
      #options:
        # Use udp://host.docker.internal:12201 when you are using Docker Desktop for Mac
        # docs: https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
        # issue: https://github.com/lvthillo/docker-elk/issues/1
        #gelf-address: "udp://localhost:12201"

networks: 
  logging-network:
    driver: overlay
